---
title: "AUMCF Simulations (Non-zero frailty Variance = 10)"
output:
  html_document: default
  pdf_document: default
date: "2025-05-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## R Markdown

```{r}
setwd('~/Documents/GitHub/AUMCF_Sim')
rm(list = ls())

# Packages.
library(optparse)
library(MCC)
library(parallel)
library(dplyr)

#source("../JACC_methods.R")
source("JACC_methods.R")
my_reps <- 5000
```

# Scenario A:  Censoring = 0.2, tau = 4 

## A1: Null 
```{r results='hide'}
params <- list(
  n = 100,
  time = 4,
  censor = 0.2,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.0,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 3,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```


## A2: Non-null (1.4)
```{r results='hide'}
params <- list(
  n = 100,
  time = 4,
  censor = 0.2,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.4,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 2,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```

\newpage

# Scenario B:  Censoring = 0.4, tau = 4 

## B1: Null 
```{r results='hide'}
params <- list(
  n = 100,
  time = 4,
  censor = 0.4,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.0,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 3,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```


## B2: Non-null (1.4)
```{r results='hide'}
params <- list(
  n = 100,
  time = 4,
  censor = 0.4,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.4,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 2,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```

\newpage
# Scenario C:  Censoring = 0.2, tau = 1 

## C1: Null 
```{r results='hide'}
params <- list(
  n = 100,
  time = 1,
  censor = 0.2,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.0,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 3,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```


## C2: Non-null (1.4)
```{r results='hide'}
params <- list(
  n = 100,
  time = 1,
  censor = 0.2,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.4,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 2,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```

\newpage

# Scenario D:  Censoring = 0.2, tau = 1

## D1: Null 
```{r results='hide'}
params <- list(
  n = 100,
  time = 1,
  censor = 0.4,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.0,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 3,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```


## D2: Non-null (1.4)
```{r results='hide'}
params <- list(
  n = 100,
  time = 1,
  censor = 0.4,
  frailtyVar = 6,
  BaseDeath0 = 0.2,
  BaseDeath1 = 0.2,
  BaseEvent0 = 1.4,
  BaseEvent1 = 1.0,
  BetaDeath = 0,
  BetaEvent = 0,
  reps = my_reps,
  adjusted = 0,
  tvr = 1.2,
  tvd = 0.2,
  experiment = 2,
  out = "Test/"
)
# Option parsing.
t0 <- proc.time()
# Output stem.
out_suffix <- paste0(
  "N", params$n, 
  "_T", params$time,
  "_l0", params$BaseEvent0,
  "_l1", params$BaseEvent1,
  "_adj", params$adjusted,
  ".rds"
)

source('test_sim_comparison.R')
```

```{r}
print(dim(sim_augmented)) # should be 2000 * 9 = 18000


print(cbind(sim_augmented %>%
              group_by(type) %>%
              summarise(Pt_est = mean(value)),
  sim_augmented %>%
              group_by(type) %>%
              summarise(Prob_reject_H0 = mean(p_value < 0.05)), 
  sim_augmented %>%
        group_by(type) %>%
        summarise(ASE = mean(se)),
        sim_augmented %>%
          group_by(type) %>%
          summarise(ESE = sd(value))
        )[, -c(3,5,7)])

```

